backend:
  name: git-gateway
  branch: main

media_folder: "projects"
public_folder: "/projects"

collections:
  - name: "projects"
    label: "Projects"
    folder: "projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Project Name", name: "title", widget: "string"}
      - {label: "Images", name: "images", widget: "list", field: {label: "Image", name: "image", widget: "image"}} 